<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>za.co.bluepearl</groupId>
    <artifactId>blue-ws</artifactId>
    <version>1.1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>Blue Web Service Contracts</name>
    <description>Generates the API Schema Model used by Blue Web Service Clients and Service Providers</description>

    <properties>
        <api.episode.file>${api.generate.directory}/META-INF/api.episode</api.episode.file>
        <api.generate.directory>${project.build.directory}/generated-sources/xjc/api</api.generate.directory>
      <java.version>11</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.10.4</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.jvnet.jaxb2.maven2</groupId>
                    <artifactId>maven-jaxb2-plugin</artifactId>
                    <version>0.14.0</version>
                </plugin>
                <plugin>
                    <groupId>org.jvnet.jax-ws-commons</groupId>
                    <artifactId>jaxws-maven-plugin</artifactId>
                    <version>2.3</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jvnet.jaxb2.maven2</groupId>
                <artifactId>maven-jaxb2-plugin</artifactId>

                <dependencies>
                    <dependency>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                        <version>2.0.1.Final</version>
                    </dependency>
                    <dependency>
                        <groupId>javax.xml.bind</groupId>
                        <artifactId>jaxb-api</artifactId>
                        <version>2.3.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.18.12</version>
                    </dependency>
                    <dependency>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-annotations</artifactId>
                        <version>2.10.4</version>
                    </dependency>
                </dependencies>

                <configuration>
                    <plugins>
                        <plugin>
                            <groupId>org.jvnet.jaxb2_commons</groupId>
                            <artifactId>jaxb2-basics</artifactId>
                            <version>1.11.1</version>
                        </plugin>
                        <plugin>
                            <groupId>org.jvnet.jaxb2_commons</groupId>
                            <artifactId>jaxb2-basics-annotate</artifactId>
                            <version>1.0.4</version>
                        </plugin>
                    </plugins>
                    <episode>true</episode>
                    <extension>true</extension>
                    <verbose>true</verbose>
                </configuration>
                <executions>
                    <execution>
                        <id>api value objects</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-Xannotate</arg>
                            </args>
                            <episodeFile>${api.episode.file}</episodeFile>
                            <strict>false</strict>
                            <schemaDirectory>src/main/xsd</schemaDirectory>
                            <schemaIncludes>
                                <include>shared/api.xsd</include>
                            </schemaIncludes>
                            <bindingDirectory>src/main/xsd/binding</bindingDirectory>
                            <bindingIncludes>
                                <include>api.xjb</include>
                            </bindingIncludes>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc/api</generateDirectory>
                            <generatePackage>za.co.bluepearl.shared.api</generatePackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>registration value objects</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-Xannotate</arg>
                            </args>
                            <strict>false</strict>
                            <schemaDirectory>src/main/xsd</schemaDirectory>
                            <schemaIncludes>
                                <include>registration/registration.xsd</include>
                            </schemaIncludes>
                            <bindingDirectory>src/main/xsd/binding</bindingDirectory>
                            <bindingIncludes>
                                <include>registration.xjb</include>
                            </bindingIncludes>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc/registration</generateDirectory>
                            <generatePackage>za.co.bluepearl.registration.dto</generatePackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>profile value objects</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <args>
                                <arg>-Xannotate</arg>
                                <arg>-b</arg>
                                <arg>${api.episode.file}</arg>
                            </args>
                            <strict>false</strict>
                            <schemaDirectory>src/main/xsd</schemaDirectory>
                            <schemaIncludes>
                                <include>profile/profile.xsd</include>
                            </schemaIncludes>
                            <bindingDirectory>src/main/xsd/binding</bindingDirectory>
                            <bindingIncludes>
                                <include>profile.xjb</include>
                            </bindingIncludes>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc/profile</generateDirectory>
                            <generatePackage>za.co.bluepearl.profile.dto</generatePackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <excludeTransitive>true</excludeTransitive>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>write-xjc-sources-to-file</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>find</executable>
                            <commandlineArgs>target/generated-sources/xjc -name "*.java" </commandlineArgs>
                            <outputFile>target/xjc-sources.txt</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-generated-xjc-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>javac</executable>
                            <commandlineArgs>-cp "${project.build.directory}/dependency/*" @target/xjc-sources.txt</commandlineArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/api.xml</descriptor>
                                <descriptor>src/main/assembly/registration.xml</descriptor>
                                <descriptor>src/main/assembly/profile.xml</descriptor>
                                <descriptor>src/main/assembly/contracts.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
