<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://www.blueapp.blue/shared/api/v1"
           targetNamespace="http://www.blueapp.blue/shared/api/v1"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
    <xs:element name="APIError" type="tns:APIError"/>

    <xs:complexType name="APIError">
        <xs:annotation>
            <xs:documentation>
                This is the default API error response message.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="timestamp" type="xs:dateTime">
                <xs:annotation>
                    <xs:documentation>The time the error happened.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="message" type="xs:string">
                <xs:annotation>
                    <xs:documentation>The description of the error message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="details" type="tns:ValidationErrors" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="ValidationErrors">
        <xs:annotation>
            <xs:documentation>
                This property holds an array of sub-errors. This is used for representing multiple errors in a single call.
                An example would be validation errors in which multiple fields have failed the validation
            </xs:documentation>
        </xs:annotation>
        <xs:list itemType="xs:string"/>
    </xs:simpleType>
</xs:schema>