<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.blueapp.blue/profile/v1"
           xmlns:tns="http://www.blueapp.blue/profile/v1"
           xmlns:api="http://www.blueapp.blue/shared/api/v1"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="http://www.blueapp.blue/shared/api/v1" schemaLocation="../shared/api.xsd"/>
    
    <xs:element name="EventLookupRequest" type="tns:EventLookupRequest"/>
    <xs:element name="EventLookupResponse" type="tns:EventLookupResponse"/>
    <xs:complexType name="EventLookupRequest">
        <xs:annotation>
            <xs:documentation>
                The request to retrieve application events.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="type" type="tns:EventType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EventLookupResponse">
        <xs:annotation>
            <xs:documentation>
                The response to an event lookup request.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="createdDate" type="xs:dateTime"/>
            <xs:element name="contractor" type="tns:ContractorReference"/>
            <xs:element name="company" type="tns:CompanyReference"/>
            <xs:element name="jobProfile" type="tns:JobProfileReference" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EventType">
        <xs:annotation>
            <xs:documentation>
                Defines the type of event.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="APPLY_FOR_JOB"/>
            <xs:enumeration value="REQUEST_INTERVIEW"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ContractorReference">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="candidateNumber" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CompanyReference">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="JobProfileReference">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Create Contract Request -->
    <xs:element name="CreateContractRequest" type="tns:CreateContractRequest"/>

    <xs:complexType name="CreateContractRequest">
        <xs:annotation>
            <xs:documentation>
                The request to create a new Contract Entity
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="eventId" type="xs:string"/>
            <xs:element name="initiatedBy" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Email address of the party that initiated this request.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="contractDurationInMonths" type="xs:int"/>
            <xs:element name="contractHoursPerMonth" type="xs:int"/>
            <xs:element name="contractStartDate" type="xs:date"/>
            <xs:element name="ratePerHourClient" type="api:MonetaryAmount"/>
            <xs:element name="ratePerHourContractor" type="api:MonetaryAmount"/>
            <xs:element name="countryCode" type="api:CountryCode"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Contract Engagement Request -->
    <xs:element name="ContractEngagementRequest" type="tns:ContractEngagementRequest"/>
    <xs:complexType name="ContractEngagementRequest">
        <xs:sequence>
            <xs:element name="eventId" type="xs:string"/>
            <xs:element name="contract" type="tns:Contract"/>
            <xs:element name="company" type="tns:CompanyReference"/>
            <xs:element name="contractor" type="tns:ContractorReference"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Contract">
        <xs:sequence>
            <xs:element name="durationInMonths" type="xs:int"/>
            <xs:element name="hoursPerMonth" type="xs:int"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="ratePerHourClient" type="api:MonetaryAmount"/>
            <xs:element name="ratePerHourContractor" type="api:MonetaryAmount"/>
            <xs:element name="countryCode" type="api:CountryCode"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>