<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://www.blueapp.blue/billing/v1"
           targetNamespace="http://www.blueapp.blue/billing/v1"
           xmlns:api="http://www.blueapp.blue/shared/api/v1"
           elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

    <xs:import namespace="http://www.blueapp.blue/shared/api/v1" schemaLocation="../shared/api.xsd"/>

    <xs:element name="TimesheetRequest" type="tns:TimesheetRequest"/>
    <xs:element name="TimesheetResponse" type="tns:TimesheetResponse"/>
    <xs:element name="TimesheetReferenceDataRequest" type="tns:TimesheetReferenceDataRequest"/>
    <xs:element name="TimesheetReferenceDataResponse" type="tns:TimesheetReferenceDataResponse"/>
    <xs:element name="CreateTimesheetEntryRequest" type="tns:CreateTimesheetEntryRequest"/>
    <xs:element name="UpdateTimesheetEntryRequest" type="tns:UpdateTimesheetEntryRequest"/>
    <xs:element name="ClientContractListRequest" type="tns:ClientContractListRequest"/>
    <xs:element name="ClientContractListResponse" type="tns:ClientContractListResponse"/>
    <xs:element name="ContractorContractListResponse" type="tns:ContractorContractListResponse"/>
    <xs:element name="QueryInvoiceRequest" type="tns:QueryInvoiceRequest"/>
    <xs:element name="QueryInvoiceListResponse" type="tns:QueryInvoiceListResponse"/>
    <xs:element name="QueryTimesheetSummaryRequest" type="tns:QueryTimesheetSummaryRequest"/>
    <xs:element name="QueryTimesheetSummaryResponse" type="tns:QueryTimesheetSummaryResponse"/>
    <xs:element name="ApproveTimesheetEntryRequest" type="tns:ApproveTimesheetEntryRequest"/>
    <xs:element name="RejectTimesheetEntryRequest" type="tns:RejectTimesheetEntryRequest"/>
    <xs:element name="TimesheetReportRequest" type="tns:TimesheetReportRequest"/>
    <xs:element name="ClientWeekViewTimesheetResponse" type="tns:ClientWeekViewTimesheetResponse"/>
    <xs:element name="ContractorWeekViewTimesheetResponse" type="tns:ContractorWeekViewTimesheetResponse"/>
    <xs:element name="ContractorBillingSummaryResponse" type="tns:ContractorBillingSummaryResponse"/>
    <xs:element name="ActivityAggregate" type="tns:ActivityAggregate"/>
    <xs:element name="CreateSubscriptionRequest" type="tns:CreateSubscriptionRequest"/>

    <xs:complexType name="TimesheetRequest">
        <xs:sequence>
            <xs:annotation>
                <xs:documentation>
                    The request to retrieve timesheets.
                    Discuss how to send through the unique identifier for the contractor.
                </xs:documentation>
            </xs:annotation>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TimesheetResponse">
        <xs:sequence>
            <xs:element name="contracts" type="tns:Contract" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Contract">
        <xs:sequence>
            <xs:element name="company" type="tns:Company"/>
            <xs:element name="timesheets" type="tns:TimesheetEntry" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Company">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Activity">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TimeLogEntry">
        <xs:sequence>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="minutes" type="xs:int">
                <xs:annotation>
                    <xs:documentation>
                        Total number of minutes
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ActivityAggregate">
        <xs:sequence>
            <xs:element name="activity" type="tns:Activity"/>
            <xs:element name="entries" type="tns:TimeLogEntry" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="TimesheetEntry">
        <xs:sequence>
            <xs:element name="id" type="xs:string" minOccurs="0"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="minutes" type="xs:int"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="activity" type="xs:string"/>
            <xs:element name="status" type="tns:TimesheetEntryStatus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TimesheetReferenceDataRequest">
        <xs:sequence>
            <xs:annotation>
                <xs:documentation>
                    The request to retrieve reference data to create timesheets.
                    Returns list of contracts and contract activities
                </xs:documentation>
            </xs:annotation>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TimesheetReferenceDataResponse">
        <xs:sequence>
            <xs:element name="contracts" type="tns:ReferenceContract" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ReferenceContract">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="company" type="tns:ReferenceCompany"/>
            <xs:element name="activities" type="tns:ReferenceActivity" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ReferenceCompany">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ReferenceActivity">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CreateTimesheetEntryRequest">
        <xs:sequence>
            <xs:element name="contractId" type="xs:string"/>
            <xs:element name="timesheet" type="tns:TimesheetEntry"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UpdateTimesheetEntryRequest">
        <xs:sequence>
            <xs:element name="timesheetId" type="xs:string"/>
            <xs:element name="timesheet" type="tns:TimesheetEntry"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TimesheetEntryStatus">
        <xs:annotation>
            <xs:documentation>
                Defines the status of a timesheet.
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="CREATED"/>
            <xs:enumeration value="APPROVED"/>
            <xs:enumeration value="REJECTED"/>
            <xs:enumeration value="BILLED"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ClientContractListRequest">
        <xs:sequence>
            <xs:element name="companyName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ClientContractListResponse">
        <xs:sequence>
            <xs:element name="clientContracts" type="tns:ClientContractSummary" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ClientContractSummary">
        <xs:sequence>
            <xs:element name="contractId" type="xs:string"/>
            <xs:element name="contractorName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ContractorContractListResponse">
        <xs:sequence>
            <xs:element name="contractorContracts" type="tns:ContractorContractSummary" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ContractorContractSummary">
        <xs:sequence>
            <xs:element name="contractId" type="xs:string"/>
            <xs:element name="companyName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="QueryInvoiceRequest">
        <xs:sequence>
            <xs:element name="contractId" type="xs:string"/>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="endDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="QueryInvoiceListResponse">
        <xs:sequence>
            <xs:element name="InvoiceListSummary" type="tns:InvoiceListSummary" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InvoiceListSummary">
        <xs:sequence>
            <xs:element name="downloadLink" type="xs:string"/>
            <xs:element name="invoiceNumber" type="xs:string"/>
            <xs:element name="contractorReference" type="xs:string"/>
            <xs:element name="invoiceDate" type="xs:date"/>
            <xs:element name="invoiceAmount" type="api:MonetaryAmount"/>
            <xs:element name="invoiceAmountIncludingVAT" type="api:MonetaryAmount"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="QueryTimesheetSummaryRequest">
        <xs:sequence>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="endDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="QueryTimesheetSummaryResponse">
        <xs:sequence>
            <xs:element name="timesheetEntries" type="tns:TimesheetEntry" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="downloadLink" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="QuerySubmittedTimesheetResponse">
        <xs:sequence>
            <xs:element name="timesheetEntries" type="tns:TimesheetEntry" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ApproveTimesheetEntryRequest">
        <xs:sequence>
            <xs:element name="timesheetEntryId" type="xs:string" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="RejectTimesheetEntryRequest">
        <xs:sequence>
            <xs:element name="timesheetEntryId" type="xs:string" />
            <xs:element name="rejectionReason" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TimesheetReportRequest">
        <xs:sequence>
            <xs:element name="startDate" type="xs:date"/>
            <xs:element name="endDate" type="xs:date"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ContractorWeekViewTimesheetResponse">
        <xs:annotation>
            <xs:documentation>
                GET Request:
                Params: startDate, endDate as type string
                Uri: /billing/contractor-timesheet-week-view/{startDate}/{endDate}
                Echos back startDate and endDate as submitted
                Returns list of ContractorTimesheetWeekView
                Contractor will be identified by email address from authorization token.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="startDate" type="xs:date" />
            <xs:element name="endDate" type="xs:date" />
            <xs:element name="rows" type="tns:ContractorTimesheetWeekView" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ClientWeekViewTimesheetResponse" >
        <xs:annotation>
            <xs:documentation>
                GET Request:
                Params: companyName, startDate, endDate as type string
                uri: /billing/client-timesheet-week-view/{companyName}/{startDate}/{endDate}
                Echos back startDate and endDate as submitted
                Returns list of ClientTimesheetWeekView
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="startDate" type="xs:date" />
            <xs:element name="endDate" type="xs:date" />
            <xs:element name="rows" type="tns:ClientTimesheetWeekView" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContractorTimesheetWeekView">
        <xs:complexContent>
            <xs:extension base="tns:TimesheetWeekView" >
                <xs:sequence>
                    <xs:element name="companyName" type="xs:string" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ClientTimesheetWeekView" >
        <xs:complexContent>
            <xs:extension base="tns:TimesheetWeekView" >
                <xs:sequence>
                    <xs:element name="contractorName" type="xs:string" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="TimesheetWeekView">
        <xs:annotation>
            <xs:documentation>
                This represents 1 row of the week view of a timesheet.
                Each row will represent 1 activity for 1 contract.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="activityAggregate" type="tns:ActivityAggregate" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContractorBillingSummaryResponse">
        <xs:annotation>
            <xs:documentation>
                GET Request:
                Params: companyName as type string
                uri: /billing/client-contractor-billing-summary/{companyName}
                Returns sum of hours per contractor for dates from start of current billing cycle start date to current date
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="contractorSummary" type="tns:ContractorBillingSummary" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ContractorBillingSummary">
        <xs:sequence>
            <xs:element name="contractorName" type="xs:string" />
            <xs:element name="totalMinutes" type="xs:int" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CreateSubscriptionRequest">
        <xs:sequence>
            <xs:element name="from" type="xs:date"/>
            <xs:element name="type" type="tns:SubscriptionType"/>
            <xs:element name="company">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="vatNumber" type="xs:string"/>
                        <xs:element name="companyId" type="xs:string"/>
                        <xs:element name="registrationToken" type="xs:string"/>
                        <xs:element name="paymentMethod" type="tns:PaymentMethod"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="SubscriptionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLUE_APP_LITE_LICENCE_FEE"/>
            <xs:enumeration value="BLUE_APP_PLUS_LICENCE_FEE"/>
            <xs:enumeration value="BLUE_APP_PREMIUM_LICENCE_FEE"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="PaymentMethod">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CREDIT_CARD"/>
            <xs:enumeration value="EFT"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>